name: Arduino Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Update board index
        run: arduino-cli core update-index

      - name: Install Nano 33 IoT core
        run: arduino-cli core install arduino:samd

      - name: Compile sketch
        run: arduino-cli compile --fqbn arduino:samd:nano_33_iot .
