name: Arduino Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Update board index
        run: arduino-cli core update-index

      - name: Install Nano 33 IoT board core
        run: arduino-cli core install arduino:samd

      - name: Install Arduino libraries
        run: |
          arduino-cli lib install "DHT sensor library"
          arduino-cli lib install "Adafruit Unified Sensor"
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "WiFiNINA"
          arduino-cli lib install "SSD1306Ascii"
          arduino-cli lib install "FreeRTOS_SAMD21"
          arduino-cli lib install "Keypad"
          arduino-cli lib install "WifiNINA"
          arduino-cli lib install "ArduinoMqttClient"
          arduino-cli lib install "MQTT"
          

      - name: Compile tempSensor sketch
        run: arduino-cli compile --fqbn arduino:samd:nano_33_iot tempSensor
